
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: SpeechBird
description: Hands-free computer control with the speed and accuracy of a keyboard and mouse.

